import "@/styles/tailwind.css";
import { Inter } from "next/font/google";
import { PropsWithChildren } from "react";

import { Footer } from "@/common/components/layout/footer";
import { Header } from "@/common/components/layout/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
